In [ ]:
'''Combinare liste e tuple con l’operatore +'''
orders_2022_02_04 = [
    (9423517,'2022-02-04',9001),
    (4626232,'2022-02-04',9003),
    (9423534,'2022-02-04',9001)
]
orders_2022_02_05 = [
    (9423679,'2022-02-05',9002),
    (4626377,'2022-02-05',9003),
    (4626412,'2022-02-05',9004)
]
orders_2022_02_06 = [
    (9423783,'2022-02-06',9002),
    (4626490,'2022-02-06',9004)
]

orders = orders_2022_02_04 + orders_2022_02_05 + orders_2022_02_06
print(orders)

'''combinare i dizionari con **'''
extra_fields_9423517 = {
    'ShippingInstructions' :
     { 'name' : 'John Silver',
      'Phone' : [{ 'type' : 'Office', 'number' : '809-123-9309' },
                 { 'type' : 'Mobile', 'number' : '417-123-4567' }
                ]}
}
order_9423517 = {'OrderNo':9423517, 'Date':'2022-02-04', 'Empno':9001}
order_9423517 = {**order_9423517, **extra_fields_9423517}
print(order_9423517)

'''Combinare righe corrispondenti di due strutture'''
details = [ 
(9423517, 'Jeans', 'Rip Curl', 87.0, 1), 
(9423517, 'Jacket', 'The North Face', 112.0, 1), 
(4626232, 'Socks', 'Vans', 15.0, 1), 
(4626232, 'Jeans', 'Quiksilver', 82.0, 1), 
(9423534, 'Socks', 'DC', 10.0, 2), 
(9423534, 'Socks', 'Quiksilver', 12.0, 2), 
(9423679, 'T-shirt', 'Patagonia', 35.0, 1), 
(4626377, 'Hoody', 'Animal', 44.0, 1), 
(4626377, 'Cargo Shorts', 'Animal', 38.0, 1), 
(4626412, 'Shirt', 'Volcom', 78.0, 1), 
(9423783, 'Boxer Shorts', 'Superdry', 30.0, 2), 
(9423783, 'Shorts', 'Globe', 26.0, 1), 
(4626490, 'Cargo Shorts', 'Billabong', 54.0, 1), 
(4626490, 'Sweater', 'Dickies', 56.0, 1)
]
#facilmente sostituibile con:
#orders_details = [[o for o in orders if d[0] == o[0]][0] + d[1:] for d in details]
orders_details = []
for o in orders:
    for d in details:
        if d[0] == o[0]:
            orders_details.append(o + d[1:])
print(orders_details)

'''Implementare diversi tipi di join per le liste'''
details.append((4626592, 'Shorts', 'Protest', 48.0, 1))
#così facendo restituisce errore:IndexError: list index out of range, poichè nella lista details manca la data
#orders_details = [[o for o in orders if d[0] == o][0] + d[1:] for d in details]
#risolviamo aggiungendo clausola if, che verifica se il num. ordine in una riga details può essere trovato i nqualiasi riga orders
#INNER JOIN
orders_details = [[o for o in orders if d[0] in o][0] + d[1:] for d in details if d[0] in [o[0] for o in orders]]
#SE SI VOLESSE INCLUDERE TUTTE LE RICGHE details NELLA LISTA orders_details con una LEFT JOIN
orders_details_right = [[o for o in orders if d[0] in o][0] + d[1:] if d[0] in [o[0] for o in orders] else (d[0], None, None) + d[1:] for d in details]
#è possibile sommare tutti gli ordini e confrontare il risultato con il totale dei soli ordini inclusi nella lista orders.
sum(pr*qt for _, _, _, _, _, pr, qt in orders_details_right)
#È possibile calcolare i totali solo degli ordini presenti in orders
sum(pr*qt for _, dt, _, _, _, pr, qt in orders_details_right if dt != None)


[(9423517, '2022-02-04', 9001), (4626232, '2022-02-04', 9003), (9423534, '2022-02-04', 9001), (9423679, '2022-02-05', 9002), (4626377, '2022-02-05', 9003), (4626412, '2022-02-05', 9004), (9423783, '2022-02-06', 9002), (4626490, '2022-02-06', 9004)]
{'OrderNo': 9423517, 'Date': '2022-02-04', 'Empno': 9001, 'ShippingInstructions': {'name': 'John Silver', 'Phone': [{'type': 'Office', 'number': '809-123-9309'}, {'type': 'Mobile', 'number': '417-123-4567'}]}}
[(9423517, '2022-02-04', 9001, 'Jeans', 'Rip Curl', 87.0, 1), (9423517, '2022-02-04', 9001, 'Jacket', 'The North Face', 112.0, 1), (4626232, '2022-02-04', 9003, 'Socks', 'Vans', 15.0, 1), (4626232, '2022-02-04', 9003, 'Jeans', 'Quiksilver', 82.0, 1), (9423534, '2022-02-04', 9001, 'Socks', 'DC', 10.0, 2), (9423534, '2022-02-04', 9001, 'Socks', 'Quiksilver', 12.0, 2), (9423679, '2022-02-05', 9002, 'T-shirt', 'Patagonia', 35.0, 1), (4626377, '2022-02-05', 9003, 'Hoody', 'Animal', 44.0, 1), (4626377, '2022-02-05', 9003, 'Cargo Shorts', 'An

779.0

In [15]:
'''Concatenare array NumPy'''
import numpy as np

jeff_salary = [2700,3000,3000] 
nick_salary = [2600,2800,2800] 
tom_salary = [2300,2500,2500] 
base_salary1 = np.array([jeff_salary, nick_salary, tom_salary])

maya_salary = [2200,2400,2400] 
john_salary = [2500,2700,2700] 
base_salary2 = np.array([maya_salary, john_salary])
#axis = 0 aggiunge il secondo array sotto il primo
base_salary = np.concatenate((base_salary1, base_salary2), axis=0)
print(base_salary)

new_month_salary = np.array([[3000],[2900],[2500],[2500],[2700]])
print(new_month_salary)
#axis = 1 consente di aggiungere i nuovi salari a destra delle colonne già inserite
base_salary = np.concatenate((base_salary, new_month_salary), axis = 1)
print(base_salary)


[[2700 3000 3000]
 [2600 2800 2800]
 [2300 2500 2500]
 [2200 2400 2400]
 [2500 2700 2700]]
[[3000]
 [2900]
 [2500]
 [2500]
 [2700]]
[[2700 3000 3000 3000]
 [2600 2800 2800 2900]
 [2300 2500 2500 2500]
 [2200 2400 2400 2500]
 [2500 2700 2700 2700]]
