In [1]:
# NUMPY cercate di trovare la media degli importi massimi pagati ogni mese a tutti i dipendenti.
import numpy as np
import pandas as pd

salario_gabri = [2000, 1900, 1950]
salario_ange = [2100, 2200, 2300]
salario_lore = [2500, 2600, 2700]

salario_totale = np.array([salario_gabri, salario_ange, salario_lore])
print(salario_totale,"\n")

bonus_gabri = [100, 200, 300]
bonus_ange = [150, 250, 350]
bonus_lore = [200, 300, 400]
bonus_totale = np.array([bonus_gabri, bonus_ange, bonus_lore])
print(bonus_totale,"\n")

salario_bonus = salario_totale + bonus_totale
print(type(salario_bonus),"\n")
print(salario_bonus,"\n")

# Trova gli importi massimi per ogni mese
massimi_mensili = np.max(salario_bonus, axis=0)
print("Importi massimi per ciascun mese:", massimi_mensili)

# Calcola la media di questi massimi
media_massimi = np.mean(massimi_mensili)
print("La media degli importi massimi pagati ogni mese a tutti i dipendenti è:", media_massimi)

#print("La media degli importi massimi pagati ogni mese a tutti i dipendenti è: ", salario_bonus.mean(axis=0,))
#print("La media degli importi massimi pagati ogni mese a tutti i dipendenti è: ", np.average(salario_bonus, axis=1))

[[2000 1900 1950]
 [2100 2200 2300]
 [2500 2600 2700]] 

[[100 200 300]
 [150 250 350]
 [200 300 400]] 

<class 'numpy.ndarray'> 

[[2100 2100 2250]
 [2250 2450 2650]
 [2700 2900 3100]] 

Importi massimi per ciascun mese: [2700 2900 3100]
La media degli importi massimi pagati ogni mese a tutti i dipendenti è: 2900.0


In [29]:
import numpy as np
array = np.arange(-3,10,0.5, dtype=int)
print(array)

array2 = np.ones((3,5)) * np.random.rand(3,5) # oppure .zeros e mette gli 0 al posto degli 1
print(array2,'\n')

array3 = np.random.rand(2,10) * 3
print(array3,'\n')

array4 = np.linspace(4,10,3)
print(array4,'\n')

[-3 -2 -1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20
 21 22]
[[0.56464801 0.50292435 0.50951288 0.27985825 0.98391685]
 [0.04704005 0.9324164  0.83088327 0.72775381 0.83178264]
 [0.9260753  0.4282816  0.54033434 0.66267689 0.38807776]] 

[[2.85825099 2.28396031 1.57392196 0.81043645 1.72655184 0.51055683
  1.30619793 0.27331554 0.40203446 1.77353219]
 [0.94004994 0.9750752  2.08947413 2.69001157 1.30431688 1.06268371
  0.50346471 1.93482673 1.03809898 2.97379803]] 

[ 4.  7. 10.] 



In [42]:
# PANDAS 
import pandas as pd

data = ['lore', 'ange', 'gabri']
emps_names = pd.Series(data)
print(emps_names,"\n")

data = ['lore', 'ange', 'gabri']
emps_names = pd.Series(data,index=[91,92,93])
print(emps_names,"\n")

print(emps_names[91],"\n")
print(emps_names.loc[91],"\n")
print(emps_names.iloc[0],"\n")
print(emps_names.loc[91:93],"\n")

print(emps_names.iloc[0:2],"\n")
print(emps_names[0:2],"\n")

# DataFrame
data = ['lore.pour', 'ange.bonhour', 'gabri.greco']
emps_emails = pd.Series(data,index=[91,92,93], name='emails')
emps_names.name = 'names'
df = pd.concat([emps_names, emps_emails], axis=1)
print(df,"\n")

#ESERCIZIO provate a creare un DataFrame da tre Series.

num = [1,2,3]
num = pd.Series(num, index=[91,92,93], name='num')
data = ['lore.pour', 'ange.bonhour', 'gabri.greco']
emps_emails = pd.Series(data,index=[91,92,93], name='emails')
emps_names = pd.Series(data,index=[91,92,93], name='names')
df = pd.concat([emps_names, emps_emails, num], axis=1)
print(df,"\n")


0     lore
1     ange
2    gabri
dtype: object 

91     lore
92     ange
93    gabri
dtype: object 

lore 

lore 

lore 

91     lore
92     ange
93    gabri
dtype: object 

91    lore
92    ange
dtype: object 

91    lore
92    ange
dtype: object 

    names        emails
91   lore     lore.pour
92   ange  ange.bonhour
93  gabri   gabri.greco 

           names        emails  num
91     lore.pour     lore.pour    1
92  ange.bonhour  ange.bonhour    2
93   gabri.greco   gabri.greco    3 



In [ ]:
# Dataframe pandas da API di Yfinance
import yfinance as yf
import pandas as pd
import json

tkr = yf.Ticker('TSLA')
hist = tkr.history(period="5d")
hist = hist.drop("Dividends", axis = 1)
hist = hist.drop("Stock Splits", axis = 1)
# per impostare index numerico
hist = hist.reset_index()

# per impostare la colonna data come indice
hist = hist.set_index('Date')

data = [
{"Empno":9001,"Salary":3000},
{"Empno":9002,"Salary":2800},
{"Empno":9003,"Salary":2500}
]
json_data = json.dumps(data)
salary = pd.read_json(json_data)
salary = salary.set_index('Empno')
print(salary)

#come creare un DataFrame da una lista di liste
data = [['9001','Jeff Russell', 'sales'],
['9002','Jane Boorman', 'sales'],
['9003','Tom Heints', 'sales']]
emps = pd.DataFrame(data, columns = ['Empno', 'Name', 'Job'])
column_types = {'Empno': int, 'Name': str, 'Job': str}
emps = emps.astype(column_types)
emps = emps.set_index('Empno')
print(emps)

# unire i due DataFrame
emps_salary = emps.join(salary)
print(emps_salary,f'\n')

# aggiungere una riga al DataFrame anche se manca il valore di un campo, uscirà NaN
new_emp = pd.Series({'Name': 'John Hardy', 'Job': 'sales'}, name = 9004)
emps = pd.concat([emps, new_emp.to_frame().T]) # nuovo metedo al posto di append in pandas 2...
print(emps,f'\n')
emps_salary = emps.join(salary)
print(emps_salary,f'\n')


       Salary
Empno        
9001     3000
9002     2800
9003     2500
               Name    Job
Empno                     
9001   Jeff Russell  sales
9002   Jane Boorman  sales
9003     Tom Heints  sales
               Name    Job  Salary
Empno                             
9001   Jeff Russell  sales    3000
9002   Jane Boorman  sales    2800
9003     Tom Heints  sales    2500 

              Name    Job
9001  Jeff Russell  sales
9002  Jane Boorman  sales
9003    Tom Heints  sales
9004    John Hardy  sales 

              Name    Job  Salary
9001  Jeff Russell  sales  3000.0
9002  Jane Boorman  sales  2800.0
9003    Tom Heints  sales  2500.0
9004    John Hardy  sales     NaN 



C:\Users\lorenzo.pourpour\AppData\Local\Temp\ipykernel_12480\2033003908.py:22: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  salary = pd.read_json(json_data)
